In [1]:
import numpy as np

In [2]:
array = np.arange(0,20,2)

In [3]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
array[0:5] #Returns elements from index 0 to 4

array([0, 2, 4, 6, 8])

In [5]:
array[1:9:2]

array([ 2,  6, 10, 14])

In [6]:
array[::2]

array([ 0,  4,  8, 12, 16])

In [7]:
array[5:]

array([10, 12, 14, 16, 18])

In [8]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
slice_of_array = array[:6] #Does not copy it to the new variable. Just generates a view.

In [10]:
slice_of_array

array([ 0,  2,  4,  6,  8, 10])

In [11]:
slice_of_array[:] = 99 

In [12]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [13]:
array # Hence the changes done to the slice_of_array are reflected here too. 

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18])

In [14]:
arr_copy = array.copy() #To copy the array, you need to explicitly use this command.

In [16]:
arr_copy

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18])

In [17]:
arr_copy[:] = 120

In [18]:
arr_copy

array([120, 120, 120, 120, 120, 120, 120, 120, 120, 120])

In [19]:
array #No changes reflected as the array is copied

array([99, 99, 99, 99, 99, 99, 12, 14, 16, 18])

In [22]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
matrix[0]

array([1, 2, 3])

In [26]:
matrix[2][1]

8

In [27]:
matrix[2,1] #Recommended

8

In [28]:
matrix[:2,:2] #Use slicing to grab top left corner

array([[1, 2],
       [4, 5]])

In [29]:
matrix[1,1:]

array([5, 6])

In [30]:
arr = np.arange(0,11)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
boole = arr>5

In [33]:
boole

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [34]:
arr[boole]

array([ 6,  7,  8,  9, 10])

In [35]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [36]:
arr = np.arange(50).reshape(5,10)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [38]:
arr[1:3,4:6]

array([[14, 15],
       [24, 25]])