In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np_array = np.array(my_list)

In [5]:
np_array

array([1, 2, 3])

In [6]:
mat = [[1,2,3],[3,4,5]]

In [7]:
np.array(mat)

array([[1, 2, 3],
       [3, 4, 5]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [24]:
np.eye(5) #Identity Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5) #5 random numbers

array([0.19882697, 0.63079754, 0.73117256, 0.41561391, 0.34213095])

In [28]:
np.random.randn(10) #Normal disrtibution numbers

array([ 0.79222859, -0.62381721, -0.56776374,  0.29057345, -1.08621703,
       -0.10332666, -1.40003693, -0.49679599,  0.62891185, -0.11539454])

In [33]:
rarr = np.array(np.random.randint(0,100,10))
rarr

array([95, 13, 65, 84, 47, 44, 73, 98, 86,  7])

In [35]:
rarr.reshape(5,2)
#Changes the shape of array. The product tuples passed must be equal to the size of array that needs to be reshaped 

array([[95, 13],
       [65, 84],
       [47, 44],
       [73, 98],
       [86,  7]])

In [36]:
rarr

array([95, 13, 65, 84, 47, 44, 73, 98, 86,  7])

In [37]:
rarr.max()

98

In [39]:
rarr.min() #Returns the minimum element

7

In [41]:
np.argmin(rarr) #Returns the location of the minimum element

9

In [43]:
np.argmax(rarr)

7

In [44]:
rarr.shape

(10,)

In [45]:
n = rarr.reshape(5,2)

In [46]:
n

array([[95, 13],
       [65, 84],
       [47, 44],
       [73, 98],
       [86,  7]])

In [49]:
n.shape #Returns the shape of array

(5, 2)

In [50]:
n.dtype #Returns the datatype

dtype('int32')