In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [7]:
arr ** 2


array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [10]:
np.sqrt(arr ** 2)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
arr / arr #A warning will show up as we try to divide 0 by 0. It will be shown as nan i.e Not A Number

c:\users\prerna\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [16]:
np.exp(arr) #Exponential of the array elements

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
np.log(arr) #Warning will pop up as we try to do log(0). The result will be -infinity.

c:\users\prerna\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [18]:
#More built in mathematical operations can be see on the documentation page of Numpy's mathematical operations

In [21]:
even = np.arange(10,51,2)

In [22]:
even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [23]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.random.rand()

0.3146469752204212

In [25]:
np.random.randn(25)

array([ 1.58172755, -1.18449678,  0.01913619, -2.32145458,  1.24965881,
       -0.19970092,  1.41106742, -0.27580455, -0.02863762, -0.18360861,
       -1.74421543,  0.68162514, -0.49023144,  2.28246983, -1.47989454,
       -0.99694317,  2.04412612, -0.77863695,  0.94449333,  1.11857046,
       -0.24983567, -1.27882568,  0.84500667,  0.4007977 , -0.55642894])

In [28]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [32]:
mat = np.arange(1,26).reshape(5,5)

In [34]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [36]:
mat[3,4]

20

In [37]:
mat[:3,1]

array([ 2,  7, 12])

In [39]:
np.sum(mat)

325

In [40]:
np.std(mat) #Standard deviation of the matrix

7.211102550927978

In [43]:
mat.sum(axis=0) #Get sum of all the coloumns

array([55, 60, 65, 70, 75])

In [44]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
mat.sum(axis=1) #Get sum of all the rows

array([ 15,  40,  65,  90, 115])